import {defineField, defineType} from 'sanity'

export const settings = defineType({
  name: 'settings',
  title: 'Instellingen',
  type: 'document',
  fields: [
    defineField({
      name: 'logo',
      title: 'Logo (navigatiebalk)',
      type: 'image',
      description: 'Upload hier het logo dat in de navigatiebalk verschijnt',
      options: {hotspot: false},
    }),
    defineField({
      name: 'heroPhoto',
      title: 'Profielfoto (startpagina)',
      type: 'image',
      description: 'Foto rechtsboven in de hero-sectie van de startpagina',
      options: {hotspot: true},
    }),
    defineField({
      name: 'getuigenissenPhoto',
      title: 'Foto (getuigenissen-pagina)',
      type: 'image',
      description: 'Foto rechts naast de intro op de pagina /getuigenissen',
      options: {hotspot: true},
    }),
    defineField({
      name: 'companyName',
      title: 'Bedrijfsnaam',
      type: 'string',
      initialValue: 'Cygnus Coaching BV',
    }),
    defineField({
      name: 'contactName',
      title: 'Contactpersoon',
      type: 'string',
      initialValue: 'Rike Weltjens',
    }),
    defineField({
      name: 'postalCode',
      title: 'Postcode',
      type: 'string',
      initialValue: '3600',
    }),
    defineField({
      name: 'city',
      title: 'Gemeente',
      type: 'string',
      initialValue: 'Genk',
    }),
    defineField({
      name: 'country',
      title: 'Land',
      type: 'string',
      initialValue: 'België',
    }),
    defineField({
      name: 'phone',
      title: 'Telefoon',
      type: 'string',
      initialValue: '+32 496 10 55 73',
    }),
    defineField({
      name: 'email',
      title: 'E-mail',
      type: 'string',
    }),
    defineField({
      name: 'tagline',
      title: 'Tagline',
      type: 'string',
      description: 'Korte slagzin onder de naam (bv. "Groei door inzicht. Kracht door coaching.")',
    }),
    defineField({
      name: 'metaDescription',
      title: 'Meta-omschrijving (SEO)',
      type: 'text',
      rows: 3,
      description: 'Omschrijving die Google toont in zoekresultaten (max. 160 tekens)',
    }),
    defineField({
      name: 'btwNummer',
      title: 'BTW-nummer',
      type: 'string',
    }),
    defineField({
      name: 'heroText',
      title: 'Hero-tekst (startpagina)',
      type: 'text',
      rows: 4,
      description: 'Leadtekst onder de hoofdtitel op de startpagina',
    }),
    defineField({
      name: 'quote',
      title: 'Belofte / korte quote (startpagina)',
      type: 'string',
      description: 'Bv. "Warm menselijk contact, scherpe vragen, en concrete stappen."',
    }),
    defineField({
      name: 'values',
      title: 'Kernwaarden',
      type: 'array',
      of: [{type: 'string'}],
      description: 'Bv. Integriteit, Vertrouwen, Respect, Passie, Engagement, Kwaliteit',
    }),
    defineField({
      name: 'specializations',
      title: 'Specialisaties / methode-tags',
      type: 'array',
      of: [{type: 'string'}],
      description: 'Bv. ICF-geïnspireerd, NLP, Stress & Burn-out, Loopbaan, Leiderschap',
    }),
    defineField({
      name: 'partners',
      title: 'Partners / erkenningen',
      type: 'array',
      of: [{type: 'string'}],
      description: 'Bv. Loopbaancheque, CERTO, WSE',
    }),
  ],
})
